version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: greet_app
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - 16379:6379
